### ISSUE TITLE
Hero API Imperius icon errors

### ISSUE THREAD

**Issue by Astraeus-** [hotsapi/hotsapi#125]
The hero API endpoints for Imperius hero icon as well as talent icons appear to not be working. I tried to get the images from these links:
[Hero icon](http://s3.hotsapi.net/img/heroes/92x93/imperius.png)
[Talent icon example](http://s3.hotsapi.net/img/talents/64x64/storm_ui_icon_imperius_q.png)

However instead I get an XML error.
![imperius talent error](https://user-images.githubusercontent.com/6303961/52575977-8020ae00-2e1f-11e9-9f0c-939a4dc9f141.png)

**Comment by AdrienGiboire** [comment]
Same goes for the following:

http://s3.hotsapi.net/img/heroes/92x93/alexstrasza.png
http://s3.hotsapi.net/img/heroes/92x93/anduin.png
http://s3.hotsapi.net/img/heroes/92x93/blaze.png
http://s3.hotsapi.net/img/heroes/92x93/deckard.png
http://s3.hotsapi.net/img/heroes/92x93/fenix.png
http://s3.hotsapi.net/img/heroes/92x93/hanzo.png
http://s3.hotsapi.net/img/heroes/92x93/imperius.png
http://s3.hotsapi.net/img/heroes/92x93/junkrat.png
http://s3.hotsapi.net/img/heroes/92x93/maiev.png
http://s3.hotsapi.net/img/heroes/92x93/malganis.png
http://s3.hotsapi.net/img/heroes/92x93/mephisto.png
http://s3.hotsapi.net/img/heroes/92x93/orphea.png
http://s3.hotsapi.net/img/heroes/92x93/whitemane.png
http://s3.hotsapi.net/img/heroes/92x93/yrel.png
http://s3.hotsapi.net/img/heroes/92x93/zuljin.png

**Comment by keanedawg** [comment]
When querying the heroes endpoint,

`cho` returns `chogall.png` rather than `cho.png` causing a bad url even though the asset does exist

**Comment by MGatner** [comment]
All image issues will be tracked and resolved by https://github.com/hotsapi/hotsapi/issues/74.
