### ISSUE TITLE
Fix jobs that fetching translation data from hotslogs.com

### ISSUE THREAD

**Issue by rjnienaber** [hotsapi/hotsapi#138]
We have scheduled commands that still retrieve translations for maps and heroes from hotslogs.com:

[fetchMaps](https://github.com/hotsapi/hotsapi/blob/52ec2cd5e17d4526c42da08f98dd507fb1ec66ab/app/Console/Commands/FetchTranslations.php#L49)
[fetchHeroes](https://github.com/hotsapi/hotsapi/blob/52ec2cd5e17d4526c42da08f98dd507fb1ec66ab/app/Console/Commands/FetchTranslations.php#L71)

Would be great if alternative translation sources could be found but I'm not sure what's currently been stored as I can't see what the current state of the database is and I don't know what the original file from hotslogs.com looked like.

**Comment by Zemill** [comment]
Likely not in the same format as the Hotslogs api calls, but we have opened up the following endpoints for public use for HotsApi.

https://api.heroesprofile.com/Heroes
https://api.heroesprofile.com/Maps

**Comment by rjnienaber** [comment]
This should be resolved by #146.
