### ISSUE TITLE
Apply preferences retroactively in the desktop app

### ISSUE THREAD

**Issue by svgPhoenix** [hotsapi/hotsapi#151]
Since the desktop app starts uploading immediately upon opening, it would be nice to have a button to retroactively apply settings changes to already-uploaded replays - especially the options to upload to HotsLogs and to delete uploaded replays

**Comment by MGatner** [comment]
Please submit as a feature request on the Uploader repo. 

https://github.com/hotsapi/Hotsapi.Uploader

**Comment by MGatner** [comment]
Under Issues is fine. Courtesy is to add “Feature:” or something to the title, of the repo owner doesn’t have tags available. Most importantly, just trying to get this on the correct repo! This one is for the website.

**Comment by svgPhoenix** [comment]
Okay thanks :)
I was pulling my hair out trying to find a feature request... *ahem* _feature_ on github :p
